# -*- coding: utf-8 -*-
"""indicNLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k1Izf5YqslhZnIj8G_tMY9eGk_MsAJmz

Here are some important NLP libraries that support Indian languages like Hindi, Gujarati, and Bengali, along with examples:

# **IndicNLP Library**: Assamese, Sindhi, Sinhala, Sanskrit, Konkani, Kannada, Telugu,Bengali,Hindi,Gujrati

-- Import Library
--Tokenization
--Transliteration:Converts text from one script to another
"""

pip install indic-nlp-library

"""# Tokenization: Splits text into tokens for processing.

"""

from indicnlp.tokenize import indic_tokenize
text = "नमस्ते, यह एक उदाहरण है।"
text2= "Hi there, I am Arghya Nath"
tokens = list(indic_tokenize.trivial_tokenize(text, lang='hi'))
tokens2 = list(indic_tokenize.trivial_tokenize(text2, lang='hi'))
print("Tokens:", tokens)
print("Tokens:",tokens2)

"""# Detokenization"""

detokenized_text = ' '.join(tokens)
print("De-tokenized Text:", detokenized_text)

"""# Transliteration:Converts text from one script to another"""

pip install indic-transliteration

from indic_transliteration import sanscript
from indic_transliteration.sanscript import transliterate

text = "नमस्ते"
transliterated_text = transliterate(text, sanscript.DEVANAGARI, sanscript.BENGALI)
transliterated_text2 = transliterate(text, sanscript.DEVANAGARI, sanscript.GUJARATI)
transliterated_text3 = transliterate(text, sanscript.DEVANAGARI, sanscript.TAMIL)
print("Bengali script:",transliterated_text)
print("Gujrati script:",transliterated_text2)
print("Tamil script:",transliterated_text3)

"""# Sentence Splitting:dividing a large text document or paragraph into individual sentences."""

from indicnlp.tokenize.sentence_tokenize import sentence_split

# Kannada Text
text = "ಇದು ಒಂದು ಉದಾಹರಣೆಯ ವಾಕ್ಯ. ಇದು ಮತ್ತೊಂದು ವಾಕ್ಯ."
text2= "বাংলা সংস্কৃতি তার বৈচিত্র্য এবং ঐতিহ্যের জন্য বিখ্যাত। এখানে সঙ্গীত, নৃত্য, শিল্প, এবং সাহিত্য গভীরভাবে মানুষের জীবনের সাথে জড়িত। রবীন্দ্রসংগীত ও লোকগীতি মানুষের অনুভূতিকে প্রকাশ করে, আর দুর্গাপূজা, যা বাঙালির প্রধান উৎসব, সমাজে আনন্দ ও ঐক্যের বার্তা নিয়ে আসে। "

# Sentence Splitting
sentences = sentence_split(text, lang='kn')
sentences2 = sentence_split(text2, lang='bn')

print("Original Text:", text)
print("Sentences:", sentences)
print("Original Text:", text2)
print("Sentences:", sentences2)

"""# Script Conversion:Allows converting text from one Indic script to another."""

from indicnlp.transliterate.unicode_transliterate import UnicodeIndicTransliterator

# Telugu Text
text = "ఇది ప్రముఖ కంప్యూటర్ సైన్స్ ప్లాట్‌ఫారమ్."

# Script Conversion (Telugu to Bengali)
converted_text = UnicodeIndicTransliterator.transliterate(text, "te", "bn")

print("Original Text:", text)
print("Converted Text:", converted_text)

!pip install indic-nlp-library

! pip install --user

from indicnlp.common.indic_chars import IndicChars

ch = "क"
print("Is consonant:", IndicChars.is_consonant(ch))  # True
print("Is vowel:", IndicChars.is_vowel(ch))  # False